apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-tawazun
  labels:
    app: mysql-tawazun
spec:
  selector:
    matchLabels:
      app: mysql-tawazun
  template:
    metadata:
      labels:
        app: mysql-tawazun
    spec:
      containers:
        - name: mysql-tawazun
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: DevOps2022
            - name: MYSQL_DATABASE
              value: tawazun  
          ports:
            - containerPort: 3306
              name: mysql-tawazun
          volumeMounts:
            - name: mysql-persistent-storagevolume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storagevolume
          persistentVolumeClaim:
            claimName: mysql-pv-claim